CREATE TABLE `TOPIC`(
    `ID` VARCHAR(255) NOT NULL,
    `TITLE` TEXT NOT NULL,
    `AUTHOR` BIGINT NOT NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    `UPDATED_AT` DATETIME(6) NOT NULL,
    CONSTRAINT `TOPIC_PK` PRIMARY KEY (`ID`)
);

CREATE TABLE `POST`(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `TEXT` TEXT NOT NULL,
    `AUTHOR` BIGINT NOT NULL,
    `TOPIC` VARCHAR(255) NOT NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    `UPDATED_AT` DATETIME(6) NOT NULL,
    CONSTRAINT `POST_PK` PRIMARY KEY (`ID`)
);

CREATE TABLE `USER`(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(255) NOT NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    `UPDATED_AT` DATETIME(6) NOT NULL,
    CONSTRAINT `USER_PK` PRIMARY KEY (`ID`)
);